#!/usr/bin/env python3
"""Generate params_dump.inc, the JSON dump of common_params used by params_driver.cpp.

The field list comes from the clang AST of common/common.h, so a field added to
common_params or to one of its nested structs shows up in the dump (and in the
goldens) without editing the driver by hand.

  params_fields.py           (rewrite params_dump.inc)
  params_fields.py --check   (fail if params_dump.inc is out of date)

Needs clang++ on PATH.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "params_dump.inc"
ROOT_STRUCT = "common_params"
HANDWRITTEN = {
    "llama_model_kv_override",
    "llama_model_tensor_buft_override",
    "llama_logit_bias",
}


def ast_objects():
    for name_filter in ("common_", "lr_opt"):
        yield from ast_dump(name_filter)


def ast_dump(name_filter):
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "ast.cpp"
        src.write_text('#include "common.h"\n')
        out = subprocess.run(
            ["clang++", "-std=c++17", "-fsyntax-only",
             "-I", ROOT / "common", "-I", ROOT / "include", "-I", ROOT / "ggml/include", "-I", ROOT / "vendor",
             "-Xclang", "-ast-dump=json", "-Xclang", f"-ast-dump-filter={name_filter}", src],
            check=True, capture_output=True, text=True).stdout
    decoder = json.JSONDecoder()
    pos = 0
    while True:
        while pos < len(out) and out[pos] != "{":
            pos += 1
        if pos >= len(out):
            return
        obj, pos = decoder.raw_decode(out, pos)
        yield obj


def records():
    found = {}
    for obj in ast_objects():
        stack = [obj]
        while stack:
            node = stack.pop()
            if node.get("kind") == "CXXRecordDecl" and node.get("completeDefinition") and "name" in node:
                fields = [(f["name"], f["type"]["qualType"]) for f in node.get("inner", []) if f.get("kind") == "FieldDecl"]
                if fields:
                    found.setdefault(node["name"], fields)
            stack.extend(node.get("inner", []))
    return found


def base_type(qual):
    t = qual.replace("const ", "").replace("struct ", "").replace("enum ", "").strip()
    for wrapper in ("std::vector<", "std::set<"):
        if t.startswith(wrapper):
            return base_type(t[len(wrapper):-1])
    return t.split("[")[0].strip()


def generate():
    recs = records()
    order, todo = [], [ROOT_STRUCT]
    while todo:
        name = todo.pop(0)
        if name in order or name in HANDWRITTEN or name not in recs:
            continue
        order.append(name)
        todo.extend(base_type(t) for _, t in recs[name])
    lines = ["// generated by params_fields.py from the clang AST of common/common.h, do not edit", ""]
    for name in order:
        lines.append(f"static json dump(const {name} & v);")
    lines.append("")
    for name in order:
        lines.append(f"static json dump(const {name} & v) {{")
        lines.append("    json j = json::object();")
        for field, _ in recs[name]:
            lines.append(f'    j["{field}"] = dump(v.{field});')
        lines.append("    return j;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main():
    text = generate()
    if sys.argv[1:] == ["--check"]:
        if OUT.read_text() != text:
            sys.exit(f"{OUT.name} is out of date, run {Path(__file__).name}")
        return
    OUT.write_text(text)


if __name__ == "__main__":
    main()
