#!/usr/bin/env python3
"""Generate the field-by-field code for common_params from the clang AST of common/common.h.

Two files come out of the same field list:
  common/params-serde.inc               CBOR encode/decode of common_params, the boundary with rust/llama-args
  scripts/rust-golden/params_dump.inc   the JSON dump params_driver uses as the oracle

  gen-common-params.py           (rewrite both files)
  gen-common-params.py --check   (fail if either file is out of date)

A field added to common_params or to one of its nested structs reaches both files, so
the Rust Params (which rejects unknown and missing fields) has to follow. Fields in
NOT_CROSSED are process-local pointers and callbacks: they never cross to Rust and
keep their C++ value on decode.

Needs clang++ on PATH.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SERDE = ROOT / "common" / "params-serde.inc"
DUMP = ROOT / "scripts" / "rust-golden" / "params_dump.inc"
ROOT_STRUCT = "common_params"
HANDWRITTEN = {
    "llama_model_kv_override",
    "llama_model_tensor_buft_override",
    "llama_logit_bias",
}
NOT_CROSSED = {
    ("common_params", "cb_eval"),
    ("common_params", "cb_eval_user_data"),
    ("common_params", "load_progress_callback"),
    ("common_params", "load_progress_callback_user_data"),
    ("common_params_speculative_draft", "ctx_tgt"),
    ("common_params_speculative_draft", "ctx_dft"),
    ("common_adapter_lora_info", "ptr"),
}


def ast_objects():
    for name_filter in ("common_", "lr_opt"):
        yield from ast_dump(name_filter)


def ast_dump(name_filter):
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "ast.cpp"
        src.write_text('#include "common.h"\n')
        out = subprocess.run(
            ["clang++", "-std=c++17", "-fsyntax-only",
             "-I", ROOT / "common", "-I", ROOT / "include", "-I", ROOT / "ggml/include", "-I", ROOT / "vendor",
             "-Xclang", "-ast-dump=json", "-Xclang", f"-ast-dump-filter={name_filter}", src],
            check=True, capture_output=True, text=True).stdout
    decoder = json.JSONDecoder()
    pos = 0
    while True:
        while pos < len(out) and out[pos] != "{":
            pos += 1
        if pos >= len(out):
            return
        obj, pos = decoder.raw_decode(out, pos)
        yield obj


def records():
    found = {}
    for obj in ast_objects():
        stack = [obj]
        while stack:
            node = stack.pop()
            if node.get("kind") == "CXXRecordDecl" and node.get("completeDefinition") and "name" in node:
                fields = [(f["name"], f["type"]["qualType"]) for f in node.get("inner", []) if f.get("kind") == "FieldDecl"]
                if fields:
                    found.setdefault(node["name"], fields)
            stack.extend(node.get("inner", []))
    return found


def base_type(qual):
    t = qual.replace("const ", "").replace("struct ", "").replace("enum ", "").strip()
    for wrapper in ("std::vector<", "std::set<"):
        if t.startswith(wrapper):
            return base_type(t[len(wrapper):-1])
    return t.split("[")[0].strip()


def struct_order(recs):
    order, todo = [], [ROOT_STRUCT]
    while todo:
        name = todo.pop(0)
        if name in order or name in HANDWRITTEN or name not in recs:
            continue
        order.append(name)
        todo.extend(base_type(t) for _, t in recs[name])
    return order


def header():
    return [f"// generated by scripts/{Path(__file__).name} from the clang AST of common/common.h, do not edit", ""]


def gen_dump(recs, order):
    lines = header()
    for name in order:
        lines.append(f"static json dump(const {name} & v);")
    lines.append("")
    for name in order:
        lines.append(f"static json dump(const {name} & v) {{")
        lines.append("    json j = json::object();")
        for field, _ in recs[name]:
            lines.append(f'    j["{field}"] = dump(v.{field});')
        lines.append("    return j;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def gen_serde(recs, order):
    lines = header()
    for name in order:
        lines.append(f"static cbor enc(const {name} & v);")
        lines.append(f"static void dec(const cbor & c, {name} & v);")
    lines.append("")
    for name in order:
        fields = [f for f, _ in recs[name] if (name, f) not in NOT_CROSSED]
        lines.append(f"static cbor enc(const {name} & v) {{")
        lines.append("    cbor c = cbor::map();")
        for field in fields:
            lines.append(f'    c.add("{field}", enc(v.{field}));')
        lines.append("    return c;")
        lines.append("}")
        lines.append("")
        lines.append(f"static void dec(const cbor & c, {name} & v) {{")
        lines.append(f'    c.expect_map("{name}", {len(fields)});')
        for field in fields:
            lines.append(f'    dec(c.at("{field}"), v.{field});')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main():
    recs = records()
    order = struct_order(recs)
    outputs = {SERDE: gen_serde(recs, order), DUMP: gen_dump(recs, order)}
    if sys.argv[1:] == ["--check"]:
        stale = [p.name for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        if stale:
            sys.exit(f"{', '.join(stale)} out of date, run scripts/{Path(__file__).name}")
        return
    for path, text in outputs.items():
        path.write_text(text)


if __name__ == "__main__":
    main()
